### ISSUE TITLE
Add support for token authentication

### ISSUE THREAD

**Issue by brunchboy** [divs1210/pushy-clj#2]
Pushy version 0.9 was released in December 2016, adding support for Apple’s new token-based authentication, which eliminates the need for certs that expire and need to be replaced each year. It would be lovely if pushy-clj could be updated to a more recent version of Pushy, and add support for this mechanism, so that we can switch to tokens and a permanent signing key.

**Comment by divs1210** [comment]
Hey, @brunchboy!
Thanks a lot for this information.
I'll get onto it asap.

**Comment by divs1210** [comment]
@brunchboy also, please star the repo if you're using it. 😄

**Comment by brunchboy** [comment]
Great, thanks for the quick response! And I have starred the repo. 👍

**Comment by divs1210** [comment]
@brunchboy I have pushed changes. Can you verify on your end?

**Comment by divs1210** [comment]
found a bug

**Comment by divs1210** [comment]
fixed ^^

**Comment by divs1210** [comment]
@brunchboy Please verify if it works for you, don't have a dev account handy at the moment.

**Comment by brunchboy** [comment]
Wow, that was fast! Thanks, I will try to test them and let you know how it goes.

**Comment by brunchboy** [comment]
Hmm… I have created a signing key, and extended my code to support configuration using that, but when I try to use your new `make-client` arity to test it, I receive this:

```
17-02-26 03:07:33 Alacrity.local INFO [com.relayrides.pushy.apns.ApnsClientBuilder:395] -
 Native SSL provider is available and supports ALPN; will use native provider.

NoSuchMethodError io.netty.bootstrap.Bootstrap.config()Lio/netty/bootstrap/BootstrapConfig; 
 com.relayrides.pushy.apns.ApnsClient.<init> (ApnsClient.java:218)
```

My code looks like this:

```clojure
(with-open [signing-key (io/input-stream (io/resource (:apns-signing-key-path (config/current))))]
  (pushy/make-client signing-key (:apns-team-id (config/current)) (:apns-key-id (config/current))
                     ["com.example.MyApp"]))
```

And even stranger… with this version, when I change configuration to go back to trying to use the certificate-based authentication, it fails like this now:

```
17-02-26 03:17:32 Alacrity.local INFO [com.relayrides.pushy.apns.ApnsClientBuilder:395] -
 Native SSL provider is available and supports ALPN; will use native provider.

NoSuchMethodError io.netty.buffer.ByteBuf.retainedSlice()Lio/netty/buffer/ByteBuf; 
 io.netty.handler.ssl.ReferenceCountedOpenSslContext.toBIO (ReferenceCountedOpenSslContext.java:736)
```

That code, which used to work, is this:

```clojure
(with-open [cert (io/input-stream  (io/resource (:apns-cert-path (config/current))))]
  (pushy/make-client cert (:apns-cert-pw (config/current))))
```

**Comment by divs1210** [comment]
Hey, @brunchboy I just released `0.3.3-SNAPSHOT` with updated netty-related dependencies.
Please try with it once.

**Comment by brunchboy** [comment]
In a quick test, the snapshot appears to work. I was able to send pushes with the signing key, and verified that even if I removed my old cert file, it still worked, so I had to be using the new code path. 👍

**Comment by divs1210** [comment]
Awesome! Releasing a non-snapshot build now.

**Comment by divs1210** [comment]
@brunchboy Done. I'm closing the ticket now.
Feel free to file support/bug tickets in the future!
Thank you!

**Comment by brunchboy** [comment]
That’s great, thanks again! When we have a chance to do some stress testing with this, we will definitely let you know if we run into any issues. It will be great to stop worrying about replacing our certificates every year once we put this version into production.

**Comment by divs1210** [comment]
@brunchboy could you tell me where you're using this?

**Comment by divs1210** [comment]
Ah, at singlewire?

**Comment by brunchboy** [comment]
Yes, with [InformaCast Mobile](https://www.singlewire.com/informacast-mobile.html).
