### ISSUE TITLE
Update to latest version of Pushy?

### ISSUE THREAD

**Issue by brunchboy** [divs1210/pushy-clj#3]
There have been some very significant bug fixes in the underlying Pushy library which make for much more stable long-term connections. Unfortunately, they also involve some significant breaking changes to the API, including changing package names due to a company name change, which will make updating pushy-clj to take advantage of them a bit of work. Is there any hope that this will be able to happen soon, or should we fork and try to do it ourselves? Thanks again for this nice wrapper!

**Comment by divs1210** [comment]
Hi @brunchboy!
I will definitely do this when I have time.
Will be difficult to do before the year ends, though.

**Comment by divs1210** [comment]
Also, feel free to submit a patch. 😃

**Comment by divs1210** [comment]
Hi, @brunchboy!
I have released `0.3.4-SNAPSHOT` with the latest version of pushy.
Please test it out and let me know if it works for you.

**Comment by divs1210** [comment]
Also, I should probably find a way to automate tests.

**Comment by brunchboy** [comment]
That’s great news, and a lovely surprise, I was planning to take a shot at doing it myself tomorrow, and submit a PR for you, but instead I will be happy to give your snapshot a try. I will absolutely let you know how it works in our environment.

**Comment by brunchboy** [comment]
I was trying to test this, but it seems like you might not have deployed the snapshot to Clojars yet?

**Comment by brunchboy** [comment]
(For the time being, I have cloned the repo and installed `0.3.4-SNAPSHOT` locally for my own testing, but of course I can’t push that to the rest of my team or use it in our Continuous Integration environment.)

**Comment by brunchboy** [comment]
Hmm. Something seems to have changed in the API which is still causing trouble. When I call `(pushy-clj.core.make-client …)` with my signing-key etc., the following exception is thrown:

    IllegalStateException No APNs server address specified.  com.turo.pushy.apns.ApnsClientBuilder.build (ApnsClientBuilder.java:478)

**Comment by brunchboy** [comment]
I am working on fixing that and will submit a pull request once I get it working. Also, the current version of Pushy is 11.3 even though the text on the project home page says 11.1, so I will fix that in the `project.clj` as well.

**Comment by brunchboy** [comment]
The problem is that we no longer call `connect()` on the `ApnsClient` instance; it manages its own connections. Because of that, there are some new mandatory configuration steps we have to make on the `ApnsClientBuilder` before we can call `build()`. I have opened an [Issue](https://github.com/relayrides/pushy/issues/565) to suggest that they make this clear in their documentation, and am working on changing the `pushy-clj` API to work in this new mode.

**Comment by brunchboy** [comment]
OK, my fixes are now available as #4

**Comment by divs1210** [comment]
Hi @brunchboy, I've added you as a collaborator. Merge your patches and ping me once you are done so I can deploy 😃

**Comment by brunchboy** [comment]
Great! They are merged, and I updated the README to show the latest version as 0.4.0. You should be able to build and deploy whenever you like, and then we can close this issue. Thanks for being so fast!

**Comment by divs1210** [comment]
@brunchboy Deployed! Nice working with you! :clinking_glasses:

**Comment by brunchboy** [comment]
Wonderful, it was very nice working with you as well, and I would not be surprised if we do it more in the future. 🤝

**Comment by divs1210** [comment]
@brunchboy It would be awesome if you could update the examples on the README to reflect API changes while you still have context, or a note to the effect that the documentation is for an older version.

**Comment by brunchboy** [comment]
I thought I had, but I will double check when I’m back at my computer.

**Comment by brunchboy** [comment]
Yes, I did this in commit https://github.com/divs1210/pushy-clj/commit/2d77aebdf233c1570fb62eddc834d767b4acf4b1

**Comment by divs1210** [comment]
Great! Thank you!

**Comment by brunchboy** [comment]
I just now added a note to warn people who are upgrading from an older version what they will need to change in their code, as well. I figured it was best not to have them surprised and confused. 😄

**Comment by divs1210** [comment]
That's great! Thanks a lot!
